{
  lib,
  pkgs,
  config,
  ...
}:
with lib;
{
  config = mkIf config.services.xserver.displayManager.gdm.enable {
    # configure gdm3 monitors.mxl
    systemd.tmpfiles.rules = [
      "L+ /run/gdm/.config/monitors.xml - - - - ${pkgs.writeText "gdm-monitors.xml" ''
        <monitors version="2">
          <configuration>
            <layoutmode>physical</layoutmode>
            <logicalmonitor>
              <x>0</x>
              <y>0</y>
              <scale>1</scale>
              <primary>yes</primary>
              <monitor>
                <monitorspec>
                  <connector>DP-1</connector>
                  <vendor>DEL</vendor>
                  <product>DELL S3220DGF</product>
                  <serial>D2FPF43</serial>
                </monitorspec>
                <mode>
                  <width>2560</width>
                  <height>1440</height>
                  <rate>165.080</rate>
                </mode>
              </monitor>
            </logicalmonitor>
            <logicalmonitor>
              <x>2560</x>
              <y>0</y>
              <scale>1</scale>
              <transform>
                <rotation>upside_down</rotation>
                <flipped>no</flipped>
              </transform>
              <monitor>
                <monitorspec>
                  <connector>DP-2</connector>
                  <vendor>DEL</vendor>
                  <product>DELL U2720QM</product>
                  <serial>7SGX623</serial>
                </monitorspec>
                <mode>
                  <width>2560</width>
                  <height>1440</height>
                  <rate>59.961</rate>
                </mode>
              </monitor>
            </logicalmonitor>
          </configuration>
          <configuration>
            <layoutmode>physical</layoutmode>
            <logicalmonitor>
              <x>1440</x>
              <y>475</y>
              <scale>1</scale>
              <primary>yes</primary>
              <monitor>
                <monitorspec>
                  <connector>DP-1</connector>
                  <vendor>DEL</vendor>
                  <product>DELL S3220DGF</product>
                  <serial>D2FPF43</serial>
                </monitorspec>
                <mode>
                  <width>2560</width>
                  <height>1440</height>
                  <rate>165.080</rate>
                </mode>
              </monitor>
            </logicalmonitor>
            <logicalmonitor>
              <x>4000</x>
              <y>475</y>
              <scale>1</scale>
              <transform>
                <rotation>upside_down</rotation>
                <flipped>no</flipped>
              </transform>
              <monitor>
                <monitorspec>
                  <connector>DP-2</connector>
                  <vendor>DEL</vendor>
                  <product>DELL U2720QM</product>
                  <serial>7SGX623</serial>
                </monitorspec>
                <mode>
                  <width>2560</width>
                  <height>1440</height>
                  <rate>59.961</rate>
                </mode>
              </monitor>
            </logicalmonitor>
            <logicalmonitor>
              <x>0</x>
              <y>0</y>
              <scale>1</scale>
              <transform>
                <rotation>left</rotation>
                <flipped>no</flipped>
              </transform>
              <monitor>
                <monitorspec>
                  <connector>DP-3</connector>
                  <vendor>DEL</vendor>
                  <product>DELL U2720QM</product>
                  <serial>3XGX623</serial>
                </monitorspec>
                <mode>
                  <width>2560</width>
                  <height>1440</height>
                  <rate>59.961</rate>
                </mode>
              </monitor>
            </logicalmonitor>
          </configuration>
        </monitors>
      ''}"
    ];
  };
}
