#!/usr/bin/env zsh
# Yabai RC File

function load() {
  denSource "etc/yabai/$1"
  return "$?"
}

# Load our framework into env
load init.rc

typeset -g space_padding=10
typeset -g window_gap=10
typeset -g external_bar=off
typeset -g external_bar_top=0
typeset -g external_bar_bottom=0
typeset -g window_border=off
typeset -g window_border_width=0
typeset -g active_border=0x00FFFFFF
typeset -g normal_border=0x00FFFFFF

typeset -ga load_extra=()

# load host specific items
load $(hostname -s).vars.rc

# Only shadow floating windows
config window_topmost off
config window_shadow on

# set mouse focus
config mouse_follows_focus off

# Get rid of auto balance
config auto_balance off

# Mouse support config
config mouse_modifier fn
config mouse_action1 move
config mouse_action2 resize
config mouse_drop_action swap


# Set the padding and gap
config top_padding $space_padding
config bottom_padding $space_padding
config left_padding $space_padding
config right_padding $space_padding
config window_gap $window_gap

config external_bar "${external_bar}:${external_bar_top}:${external_bar_bottom}"

# Window Borders
config window_border $window_border
config window_border_width $window_border_width
config active_window_border_color $active_border
config normal_window_border_color $normal_border

# set the layout to bsp
config layout bsp

# Load in our app rules
load apps.rc

for f in "${load_extra[@]}"; do
  load "$f"
done

# Make things happen
commit
