#!/usr/bin/env zsh
# Yabai RC File

BASEDIR=${0:h:A}
function load() {
  source $BASEDIR/$1
}

DOT=$(dirname $(dirname $BASEDIR))

# Load our framework into env
load init.rc

# Only shadow floating windows
config window_topmost off
config window_shadow on

# set mouse focus
config mouse_follows_focus off

# Get rid of auto balance
config auto_balance off

# Mouse support config
config mouse_modifier fn
config mouse_action1 move
config mouse_action2 resize
config mouse_drop_action swap

# load host specific items
load $(uname -n).host.rc

# set the layout to bsp
config layout bsp

# Load in our app rules
load apps.rc

# Make things happen
commit
