
function dotLoad() {
	if [ -f "$DOT/$1" ]; then
		source "$DOT/$1"
		return 0
	fi
	printf "i am sorry. i could not find your file '$1' in '$DOT'"
	return 1
}

export DOT="$HOME/dot"

export XDG_CONFIG_HOME="$DOT/etc"

export PATH="$DOT/bin:$HOME/bin:$PATH"

