export GOPATH="$HOME/go"

export DOT="$HOME/workspace/noriah/dot"

function dotLoad() {
	if [ -f "$DOT/$1" ]; then
		source "$DOT/$1"
		return 0
	fi
	return 1
}

export PATH="$HOME/.npm-global/bin:$HOME/go/bin:$DOT/bin:$HOME/bin:/usr/local/sbin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"

