#!/usr/bin/env zsh

function denAsk() {
	local action="$1"
	local item="$2"
	shift 2

	case "$action" in
		install)
			read -q "choice? *** Would you like to install ${item}? (y/n)"
			y=$?
			echo
			return "$y"

			;;
		*)
			return 1
			;;
	esac

	return 0
}
