#!/usr/bin/env zsh

function denRepo() {
	if [ ! -d "$DEN/opt" ]; then
		mkdir -p "$DEN/opt"
	fi

	local repoURL="https://github.com/$1"
	local repoDir="$DEN/opt/$2"

	if [[ ! -d "$repoDir" || ! -d "$repoDir/.git" ]]; then
		denAsk install "$2" || return 1
		git clone "$repoURL" "$repoDir" || return 1
	fi

	export DEN_REPO_PATH="$repoDir"

	return 0
}
