fonts:
  icons: 3

trimet:
  appId: 'key'
  stopIds:
    - '0'
    - '1'
    - '2'

weather:
  aqi:
    apiKey: 'key'
    city: A123456
  forecast:
    apiKey: 'key'
    city: '123456'
    units: both
