#!/bin/sh

# dex --autostart --environment i3

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec xss-lock --transfer-sleep-lock -- i3lock.sh

# Composter
exec DISPLAY=":0" picom -b --backend xrender

# DBus Stuffs
exec dbus-update-activation-environment --all --systemd

# DSP
exec jamesdsp --tray

# Bluetooth Manager
exec blueman-applet

# Password Manager
exec 1password --silent

# Polkit Agent
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# set backgrounds
exec nitrogen --restore
