{ ... }:
{
  imports = [
    ./_1password.nix
    ./alacritty.nix
    ./albert.nix
    ./budgie.nix
    ./firefox.nix
    ./git.nix
    ./gnome.nix
    ./go.nix
    ./helix.nix
    ./hyprland.nix
    ./i3.nix
    ./jamesdsp.nix
    ./julia.nix
    ./neofetch.nix
    ./openrgb.nix
    ./picom.nix
    ./polybar.nix
    ./rust.nix
    ./spotify.nix
    ./syncthing.nix
    ./tmux.nix
    ./tor.nix
    ./ulauncher.nix
    ./vim.nix
    ./vscode.nix
    ./wezterm.nix
  ];
}
