; Host specific config for ersa

[displays]
primary = DP-2
secondary = DP-0
tertiary = HDMI-0


[modules]
primary-top-left = symbol sep
primary-top-center = player player-controls
primary-top-right = sep pipewire-control-jamesdsp sep forecast aqi sep date time

primary-bottom-left =  i3 i3-mode sep cpu memory sep nvidia-smi-all sep
primary-bottom-center =
primary-bottom-right = sep loadavg sep uptime sep kernel-release sep

secondary-top-left = symbol sep
secondary-top-center = player player-controls
secondary-top-right = sep pipewire-control-jamesdsp sep date time

secondary-bottom-left = i3 i3-mode sep
secondary-bottom-center =
secondary-bottom-right =

tertiary-top-left = symbol sep
tertiary-top-center = player player-controls
tertiary-top-right = sep pipewire-control-jamesdsp sep date time

tertiary-bottom-left = i3 i3-mode sep
tertiary-bottom-center =
tertiary-bottom-right =
