# Common Stuff
export HOME_ETC="$HOME/etc"
export HOME_OPT="$HOME/opt"
export HOME_TMP="$HOME/tmp"
export HOME_USR="$HOME/usr"
export HOME_VAR="$HOME/var"

export FOX_DEN="$(dirname "$(dirname "${0:h:A}")")"

export CACHE_DIR="$HOME_VAR/cache"
export ZSH_CACHE_DIR="$CACHE_DIR/zsh"

export XDG_CACHE_HOME="$CACHE_DIR"
export XDG_DATA_HOME="$HOME_VAR"

###
# Paths
#
# Need to be set in environment because scripts don't load rc.
# Scripts may run commands using these paths.

# Go
export GO_PATH="$HOME_OPT/go"
export GOPATH="$GO_PATH"

# Node
export NPM_PATH="$HOME_OPT/npm"
export NPM_CONFIG_CACHE="$NPM_PATH/cache"

# Rust
export CARGO_HOME="$HOME_OPT/cargo"

# Ruby
export GEM_PATH="$HOME_OPT/gem/ruby/2.6.0"

# Dart
export DART_PUB_PATH="$HOME_OPT/pub-cache"
export PUB_CACHE="$DART_PUB_PATH"

if [ ${FOX_DEN_ZSHENV_RUN:=0} -ne 1 ]; then

  # We need some paths. Let us have paths
  paths=(
    HOME
    FOX_DEN
    GO_PATH
    NPM_PATH
    CARGO_HOME
    GEM_PATH
    DART_PUB_PATH
  )

  # Export our path paths in the PATH]
  for p in "${paths[@]}"; do
    p="${(P)p}/bin"
    [ -d "$p" ] && export PATH="$PATH:$p"
  done

  unset paths

  export FOX_DEN_ZSHENV_RUN=1
fi
