# zsh entry point

[ ! -d "$ZSH_CACHE_DIR" ] && mkdir "$ZSH_CACHE_DIR"

# load den
. "$FOX_DEN/usr/foxden/rc.zsh"

# load our home
den::conf home.zsh

# aliases
den::source etc/zsh/zaliases

if [ -f ~/.zaliases ]; then
  . ~/.zaliases
fi

export FOX_DEN_ZSHRC_RUN=1
