export PATH="/usr/local/sbin:$PATH"

denSource etc/sh/profile

# We need some paths. Let us have paths
paths=(
	# Reverse order so we get bottom at first search
	GEM_PATH
	CARGO_PATH
	NPM_PATH
	GO_PATH
	DOTS
	HOME
)

# Export our path paths in the PATH]
for p in "${paths[@]}"; do
	p="${(P)p}/bin"
	[ -d "$p" ] && export PATH="$p:$PATH"
done

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

denSource usr/foxden/rc.zsh

# load our home
denConf home.rc
