# monitor.alsa.rules = [
#   {
#     matches = [
#       # {
#       #   node.name = ""
#       # }
#       # {
#       #   node.name = ""
#       # }
#     ]
#     actions = {
#       update-props = {
#          node.disabled = true
#       }
#     }
#   }
# ]
