#!/usr/bin/env zsh
# Yabai RC File

BASEDIR=$(dirname "$0")
function load() {
  source $BASEDIR/$1
}

# Load our framework into env
load init.rc

pad='30'

# Set the padding and gap
config top_padding $pad
config bottom_padding $pad
config left_padding $pad
config right_padding $pad
config window_gap $pad

config external_bar main:0:150

# Only shadow floating windows
config window_topmost off
config window_shadow float

# set mouse focus
config mouse_follows_focus on

# Window Borders
config window_border on
config window_border_width 10
config active_window_border_color 0xFFFB7BA1
config normal_window_border_color 0x00314484

# Get rid of auto balance
config auto_balance off

# Mouse support config
config mouse_modifier fn
config mouse_action1 move
config mouse_action2 resize
config mouse_drop_action swap

# set the layout to bsp
config layout bsp

# Load in our app rules
load apps.rc

# Make things happen
commit
